<?php

namespace Database\Seeders;


use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        DB::Table('products')->insert([
            [
                'id_product'=>1,
                'detail'=>'Mob Psycho 1',
                'description'=>'Shigeo Kageyama (alias Mob) es un estudiante de secundaria que anhela vivir una adolescencia normal. Pero no le va a resultar tan fácil, ya que es distinto a los demás adolescentes de su colegio, porque tiene… ¡¡poderes psíquicos!! Empezó doblando cucharas y moviendo cosas con la mente. Gradualmente fue capaz de ir haciendo más y más, pero decidió ocultar sus habilidades para no llamar la atención. Ahora, lo único que le interesa es que una compañera, Tsubomi, le dé bola. Con la ayuda del chanta encantador de Reigen, su “mentor psíquico” que ni siquiera tiene poderes, va a tratar de cumplir con sus sueños de normalidad aunque tenga que pelearse con fantasmas y demonios en el intento.',
                'price'=>1500,
                'image'=>'mob1.jpg',
                'id_provider'=>1,
                'id_country'=>7,
                'date'=>date('Y-m-d H:i:s'),
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'id_product'=>2,
                'detail'=>'Mob Psycho 2',
                'description'=>'Shigeo Kageyama (alias Mob) es un estudiante de secundaria que anhela vivir una adolescencia normal. Pero no le va a resultar tan fácil, ya que es distinto a los demás adolescentes de su colegio, porque tiene… ¡¡poderes psíquicos!! Empezó doblando cucharas y moviendo cosas con la mente. Gradualmente fue capaz de ir haciendo más y más, pero decidió ocultar sus habilidades para no llamar la atención. Ahora, lo único que le interesa es que una compañera, Tsubomi, le dé bola. Con la ayuda del chanta encantador de Reigen, su “mentor psíquico” que ni siquiera tiene poderes, va a tratar de cumplir con sus sueños de normalidad aunque tenga que pelearse con fantasmas y demonios en el intento.',
                'price'=>1500,
                'image'=>'mob2.jpg',
                'id_provider'=>1,
                'id_country'=>7,
                'date'=>date('Y-m-d H:i:s'),
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'id_product'=>3,
                'detail'=>'Mob Psycho 3',
                'description'=>'Shigeo Kageyama (alias Mob) es un estudiante de secundaria que anhela vivir una adolescencia normal. Pero no le va a resultar tan fácil, ya que es distinto a los demás adolescentes de su colegio, porque tiene… ¡¡poderes psíquicos!! Empezó doblando cucharas y moviendo cosas con la mente. Gradualmente fue capaz de ir haciendo más y más, pero decidió ocultar sus habilidades para no llamar la atención. Ahora, lo único que le interesa es que una compañera, Tsubomi, le dé bola. Con la ayuda del chanta encantador de Reigen, su “mentor psíquico” que ni siquiera tiene poderes, va a tratar de cumplir con sus sueños de normalidad aunque tenga que pelearse con fantasmas y demonios en el intento.',
                'price'=>1500,
                'image'=>'mob3.jpg',
                'id_provider'=>1,
                'id_country'=>7,
                'date'=>date('Y-m-d H:i:s'),
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'id_product'=>4,
                'detail'=>'Mob Psycho 4',
                'description'=>'Shigeo Kageyama (alias Mob) es un estudiante de secundaria que anhela vivir una adolescencia normal. Pero no le va a resultar tan fácil, ya que es distinto a los demás adolescentes de su colegio, porque tiene… ¡¡poderes psíquicos!! Empezó doblando cucharas y moviendo cosas con la mente. Gradualmente fue capaz de ir haciendo más y más, pero decidió ocultar sus habilidades para no llamar la atención. Ahora, lo único que le interesa es que una compañera, Tsubomi, le dé bola. Con la ayuda del chanta encantador de Reigen, su “mentor psíquico” que ni siquiera tiene poderes, va a tratar de cumplir con sus sueños de normalidad aunque tenga que pelearse con fantasmas y demonios en el intento.',
                'price'=>1500,
                'image'=>'mob4.jpg',
                'id_provider'=>1,
                'id_country'=>7,
                'date'=>date('Y-m-d H:i:s'),
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'id_product'=>5,
                'detail'=>'Alice in Borderland 1',
                'description'=>'Llega unos de los mangas survival que más ha dado que hablar este año gracias a su genial adaptación a live action emitida en Netflix. Una historia repleta de acción, suspense y macabros juegos, protagonizada por tres amigos que acaban teletransportados a un mundo paralelo aparentemente igual que el nuestro, pero sólo habitado por aquellos desafortunados que están obligados a participar en el juego de supervivencia.',
                'price'=>2000,
                'image'=>'aliceinborderland01.jpg',
                'id_provider'=>1,
                'id_country'=>7,
                'date'=>date('Y-m-d H:i:s'),
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'id_product'=>6,
                'detail'=>'Alice in Borderland 2',
                'description'=>'Llega unos de los mangas survival que más ha dado que hablar este año gracias a su genial adaptación a live action emitida en Netflix. Una historia repleta de acción, suspense y macabros juegos, protagonizada por tres amigos que acaban teletransportados a un mundo paralelo aparentemente igual que el nuestro, pero sólo habitado por aquellos desafortunados que están obligados a participar en el juego de supervivencia.',
                'price'=>2000,
                'image'=>'aliceinborderland02.jpg',
                'id_provider'=>1,
                'id_country'=>7,
                'date'=>date('Y-m-d H:i:s'),
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'id_product'=>7,
                'detail'=>'Alice in Borderland 3',
                'description'=>'Llega unos de los mangas survival que más ha dado que hablar este año gracias a su genial adaptación a live action emitida en Netflix. Una historia repleta de acción, suspense y macabros juegos, protagonizada por tres amigos que acaban teletransportados a un mundo paralelo aparentemente igual que el nuestro, pero sólo habitado por aquellos desafortunados que están obligados a participar en el juego de supervivencia.',
                'price'=>2000,
                'image'=>'aliceinborderland03.jpg',
                'id_provider'=>1,
                'id_country'=>7,
                'date'=>date('Y-m-d H:i:s'),
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'id_product'=>8,
                'detail'=>'Blue Lock 1',
                'description'=>'Mezclando dos temáticas super populares como son el fútbol y el battle royale, los autores cuentan una historia llena de intriga, emoción y acción que busca cautivar tanto a los fans del futbol como a todo lector que busque una historia atraparte y diferente. Tras quedar eliminados de la copa del mundo de 2018 y sintiendo que la capacidad de sus jugadores ha llegado a un límite, las autoridades de la Asociación de Fútbol Japonesa están dispuestas a todo para lograr conseguir lo que, ellos creen, es lo único que necesitan para poder competir en igualdad de condiciones contra las selecciones más poderosas del planeta: un delantero estrella. Así, ponen en marcha el proyecto Blue Lock, un centro de capacitación donde someterán a un gran número de adolescentes con potencial para el deporte a un riguroso y extremo entrenamiento que los llevará a pelear por convertirse en el mejor delantero del mundo, aún poniendo en riesgos sus propias carreras.',
                'price'=>2000,
                'image'=>'bluelock01.jpg',
                'id_provider'=>1,
                'id_country'=>7,
                'date'=>date('Y-m-d H:i:s'),
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'id_product'=>9,
                'detail'=>'Blue Lock 2',
                'description'=>'Mezclando dos temáticas super populares como son el fútbol y el battle royale, los autores cuentan una historia llena de intriga, emoción y acción que busca cautivar tanto a los fans del futbol como a todo lector que busque una historia atraparte y diferente. Tras quedar eliminados de la copa del mundo de 2018 y sintiendo que la capacidad de sus jugadores ha llegado a un límite, las autoridades de la Asociación de Fútbol Japonesa están dispuestas a todo para lograr conseguir lo que, ellos creen, es lo único que necesitan para poder competir en igualdad de condiciones contra las selecciones más poderosas del planeta: un delantero estrella. Así, ponen en marcha el proyecto Blue Lock, un centro de capacitación donde someterán a un gran número de adolescentes con potencial para el deporte a un riguroso y extremo entrenamiento que los llevará a pelear por convertirse en el mejor delantero del mundo, aún poniendo en riesgos sus propias carreras.',
                'price'=>2000,
                'image'=>'bluelock02.jpg',
                'id_provider'=>1,
                'id_country'=>7,
                'date'=>date('Y-m-d H:i:s'),
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'id_product'=>10,
                'detail'=>'Blue Lock 3',
                'description'=>'Mezclando dos temáticas super populares como son el fútbol y el battle royale, los autores cuentan una historia llena de intriga, emoción y acción que busca cautivar tanto a los fans del futbol como a todo lector que busque una historia atraparte y diferente. Tras quedar eliminados de la copa del mundo de 2018 y sintiendo que la capacidad de sus jugadores ha llegado a un límite, las autoridades de la Asociación de Fútbol Japonesa están dispuestas a todo para lograr conseguir lo que, ellos creen, es lo único que necesitan para poder competir en igualdad de condiciones contra las selecciones más poderosas del planeta: un delantero estrella. Así, ponen en marcha el proyecto Blue Lock, un centro de capacitación donde someterán a un gran número de adolescentes con potencial para el deporte a un riguroso y extremo entrenamiento que los llevará a pelear por convertirse en el mejor delantero del mundo, aún poniendo en riesgos sus propias carreras.',
                'price'=>2000,
                'image'=>'bluelock03.jpg',
                'id_provider'=>1,
                'id_country'=>7,
                'date'=>date('Y-m-d H:i:s'),
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'id_product'=>11,
                'detail'=>'Blue Lock 4',
                'description'=>'Mezclando dos temáticas super populares como son el fútbol y el battle royale, los autores cuentan una historia llena de intriga, emoción y acción que busca cautivar tanto a los fans del futbol como a todo lector que busque una historia atraparte y diferente. Tras quedar eliminados de la copa del mundo de 2018 y sintiendo que la capacidad de sus jugadores ha llegado a un límite, las autoridades de la Asociación de Fútbol Japonesa están dispuestas a todo para lograr conseguir lo que, ellos creen, es lo único que necesitan para poder competir en igualdad de condiciones contra las selecciones más poderosas del planeta: un delantero estrella. Así, ponen en marcha el proyecto Blue Lock, un centro de capacitación donde someterán a un gran número de adolescentes con potencial para el deporte a un riguroso y extremo entrenamiento que los llevará a pelear por convertirse en el mejor delantero del mundo, aún poniendo en riesgos sus propias carreras.',
                'price'=>2000,
                'image'=>'bluelock04.jpg',
                'id_provider'=>1,
                'id_country'=>7,
                'date'=>date('Y-m-d H:i:s'),
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'id_product'=>12,
                'detail'=>'Chainsaw Man 1',
                'description'=>'Cuando su padre murió, Denji se vio obligado a saldar una gran deuda y no había forma de pagarla. Pero gracias a la ayuda de un Demonio Perro que salvó llamado Pochita, Denji es capaz de sobrevivir convirtiéndose en un Cazador de demonios a sueldo, haciendo trabajos para los Yakuza. Los poderes motosierra de Pochita son útiles contra estos poderosos demonios. Y cuando Denji termina siendo asesinado por un demonio, Pochita se sacrifica para revivirlo. Pero ahora Denji ha renacido como una especie de extraño híbrido Demonio-Humano. ¡Ahora es Chainsaw Man! Después de su transformación, es reclutado rápidamente y obligado a unirse a los Cazadores de Demonios de Seguridad Pública bajo amenaza de exterminio ya que técnicamente es un Demonio. Ahora que vive cómodamente por primera vez en su vida, Denji lucha por determinar sus sueños y establecer relaciones significativas mientras mata demonios y trabaja junto a otros excéntricos cazadores.',
                'price'=>2000,
                'image'=>'chainsawman01.jpg',
                'id_provider'=>1,
                'id_country'=>7,
                'date'=>date('Y-m-d H:i:s'),
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'id_product'=>13,
                'detail'=>'Chainsaw Man 2',
                'description'=>'Cuando su padre murió, Denji se vio obligado a saldar una gran deuda y no había forma de pagarla. Pero gracias a la ayuda de un Demonio Perro que salvó llamado Pochita, Denji es capaz de sobrevivir convirtiéndose en un Cazador de demonios a sueldo, haciendo trabajos para los Yakuza. Los poderes motosierra de Pochita son útiles contra estos poderosos demonios. Y cuando Denji termina siendo asesinado por un demonio, Pochita se sacrifica para revivirlo. Pero ahora Denji ha renacido como una especie de extraño híbrido Demonio-Humano. ¡Ahora es Chainsaw Man! Después de su transformación, es reclutado rápidamente y obligado a unirse a los Cazadores de Demonios de Seguridad Pública bajo amenaza de exterminio ya que técnicamente es un Demonio. Ahora que vive cómodamente por primera vez en su vida, Denji lucha por determinar sus sueños y establecer relaciones significativas mientras mata demonios y trabaja junto a otros excéntricos cazadores.',
                'price'=>2000,
                'image'=>'chainsawman02.jpg',
                'id_provider'=>1,
                'id_country'=>7,
                'date'=>date('Y-m-d H:i:s'),
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'id_product'=>14,
                'detail'=>'Chainsaw Man 3',
                'description'=>'Cuando su padre murió, Denji se vio obligado a saldar una gran deuda y no había forma de pagarla. Pero gracias a la ayuda de un Demonio Perro que salvó llamado Pochita, Denji es capaz de sobrevivir convirtiéndose en un Cazador de demonios a sueldo, haciendo trabajos para los Yakuza. Los poderes motosierra de Pochita son útiles contra estos poderosos demonios. Y cuando Denji termina siendo asesinado por un demonio, Pochita se sacrifica para revivirlo. Pero ahora Denji ha renacido como una especie de extraño híbrido Demonio-Humano. ¡Ahora es Chainsaw Man! Después de su transformación, es reclutado rápidamente y obligado a unirse a los Cazadores de Demonios de Seguridad Pública bajo amenaza de exterminio ya que técnicamente es un Demonio. Ahora que vive cómodamente por primera vez en su vida, Denji lucha por determinar sus sueños y establecer relaciones significativas mientras mata demonios y trabaja junto a otros excéntricos cazadores.',
                'price'=>2000,
                'image'=>'chainsawman03.jpg',
                'id_provider'=>1,
                'id_country'=>7,
                'date'=>date('Y-m-d H:i:s'),
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'id_product'=>15,
                'detail'=>'Chainsaw Man 4',
                'description'=>'Cuando su padre murió, Denji se vio obligado a saldar una gran deuda y no había forma de pagarla. Pero gracias a la ayuda de un Demonio Perro que salvó llamado Pochita, Denji es capaz de sobrevivir convirtiéndose en un Cazador de demonios a sueldo, haciendo trabajos para los Yakuza. Los poderes motosierra de Pochita son útiles contra estos poderosos demonios. Y cuando Denji termina siendo asesinado por un demonio, Pochita se sacrifica para revivirlo. Pero ahora Denji ha renacido como una especie de extraño híbrido Demonio-Humano. ¡Ahora es Chainsaw Man! Después de su transformación, es reclutado rápidamente y obligado a unirse a los Cazadores de Demonios de Seguridad Pública bajo amenaza de exterminio ya que técnicamente es un Demonio. Ahora que vive cómodamente por primera vez en su vida, Denji lucha por determinar sus sueños y establecer relaciones significativas mientras mata demonios y trabaja junto a otros excéntricos cazadores.',
                'price'=>2000,
                'image'=>'chainsawman04.jpg',
                'id_provider'=>1,
                'id_country'=>7,
                'date'=>date('Y-m-d H:i:s'),
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'id_product'=>16,
                'detail'=>'Chainsaw Man 5',
                'description'=>'Cuando su padre murió, Denji se vio obligado a saldar una gran deuda y no había forma de pagarla. Pero gracias a la ayuda de un Demonio Perro que salvó llamado Pochita, Denji es capaz de sobrevivir convirtiéndose en un Cazador de demonios a sueldo, haciendo trabajos para los Yakuza. Los poderes motosierra de Pochita son útiles contra estos poderosos demonios. Y cuando Denji termina siendo asesinado por un demonio, Pochita se sacrifica para revivirlo. Pero ahora Denji ha renacido como una especie de extraño híbrido Demonio-Humano. ¡Ahora es Chainsaw Man! Después de su transformación, es reclutado rápidamente y obligado a unirse a los Cazadores de Demonios de Seguridad Pública bajo amenaza de exterminio ya que técnicamente es un Demonio. Ahora que vive cómodamente por primera vez en su vida, Denji lucha por determinar sus sueños y establecer relaciones significativas mientras mata demonios y trabaja junto a otros excéntricos cazadores.',
                'price'=>2000,
                'image'=>'chainsawman05.jpg',
                'id_provider'=>1,
                'id_country'=>7,
                'date'=>date('Y-m-d H:i:s'),
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'id_product'=>17,
                'detail'=>'Chainsaw Man 6',
                'description'=>'Cuando su padre murió, Denji se vio obligado a saldar una gran deuda y no había forma de pagarla. Pero gracias a la ayuda de un Demonio Perro que salvó llamado Pochita, Denji es capaz de sobrevivir convirtiéndose en un Cazador de demonios a sueldo, haciendo trabajos para los Yakuza. Los poderes motosierra de Pochita son útiles contra estos poderosos demonios. Y cuando Denji termina siendo asesinado por un demonio, Pochita se sacrifica para revivirlo. Pero ahora Denji ha renacido como una especie de extraño híbrido Demonio-Humano. ¡Ahora es Chainsaw Man! Después de su transformación, es reclutado rápidamente y obligado a unirse a los Cazadores de Demonios de Seguridad Pública bajo amenaza de exterminio ya que técnicamente es un Demonio. Ahora que vive cómodamente por primera vez en su vida, Denji lucha por determinar sus sueños y establecer relaciones significativas mientras mata demonios y trabaja junto a otros excéntricos cazadores.',
                'price'=>2000,
                'image'=>'chainsawman06.jpg',
                'id_provider'=>1,
                'id_country'=>7,
                'date'=>date('Y-m-d H:i:s'),
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'id_product'=>18,
                'detail'=>'Chainsaw Man 7',
                'description'=>'Cuando su padre murió, Denji se vio obligado a saldar una gran deuda y no había forma de pagarla. Pero gracias a la ayuda de un Demonio Perro que salvó llamado Pochita, Denji es capaz de sobrevivir convirtiéndose en un Cazador de demonios a sueldo, haciendo trabajos para los Yakuza. Los poderes motosierra de Pochita son útiles contra estos poderosos demonios. Y cuando Denji termina siendo asesinado por un demonio, Pochita se sacrifica para revivirlo. Pero ahora Denji ha renacido como una especie de extraño híbrido Demonio-Humano. ¡Ahora es Chainsaw Man! Después de su transformación, es reclutado rápidamente y obligado a unirse a los Cazadores de Demonios de Seguridad Pública bajo amenaza de exterminio ya que técnicamente es un Demonio. Ahora que vive cómodamente por primera vez en su vida, Denji lucha por determinar sus sueños y establecer relaciones significativas mientras mata demonios y trabaja junto a otros excéntricos cazadores.',
                'price'=>2000,
                'image'=>'chainsawman07.jpg',
                'id_provider'=>1,
                'id_country'=>7,
                'date'=>date('Y-m-d H:i:s'),
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'id_product'=>19,
                'detail'=>'Chainsaw Man 8',
                'description'=>'Cuando su padre murió, Denji se vio obligado a saldar una gran deuda y no había forma de pagarla. Pero gracias a la ayuda de un Demonio Perro que salvó llamado Pochita, Denji es capaz de sobrevivir convirtiéndose en un Cazador de demonios a sueldo, haciendo trabajos para los Yakuza. Los poderes motosierra de Pochita son útiles contra estos poderosos demonios. Y cuando Denji termina siendo asesinado por un demonio, Pochita se sacrifica para revivirlo. Pero ahora Denji ha renacido como una especie de extraño híbrido Demonio-Humano. ¡Ahora es Chainsaw Man! Después de su transformación, es reclutado rápidamente y obligado a unirse a los Cazadores de Demonios de Seguridad Pública bajo amenaza de exterminio ya que técnicamente es un Demonio. Ahora que vive cómodamente por primera vez en su vida, Denji lucha por determinar sus sueños y establecer relaciones significativas mientras mata demonios y trabaja junto a otros excéntricos cazadores.',
                'price'=>2000,
                'image'=>'chainsawman08.jpg',
                'id_provider'=>1,
                'id_country'=>7,
                'date'=>date('Y-m-d H:i:s'),
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'id_product'=>20,
                'detail'=>'Chainsaw Man 9',
                'description'=>'Cuando su padre murió, Denji se vio obligado a saldar una gran deuda y no había forma de pagarla. Pero gracias a la ayuda de un Demonio Perro que salvó llamado Pochita, Denji es capaz de sobrevivir convirtiéndose en un Cazador de demonios a sueldo, haciendo trabajos para los Yakuza. Los poderes motosierra de Pochita son útiles contra estos poderosos demonios. Y cuando Denji termina siendo asesinado por un demonio, Pochita se sacrifica para revivirlo. Pero ahora Denji ha renacido como una especie de extraño híbrido Demonio-Humano. ¡Ahora es Chainsaw Man! Después de su transformación, es reclutado rápidamente y obligado a unirse a los Cazadores de Demonios de Seguridad Pública bajo amenaza de exterminio ya que técnicamente es un Demonio. Ahora que vive cómodamente por primera vez en su vida, Denji lucha por determinar sus sueños y establecer relaciones significativas mientras mata demonios y trabaja junto a otros excéntricos cazadores.',
                'price'=>2000,
                'image'=>'chainsawman09.jpg',
                'id_provider'=>1,
                'id_country'=>7,
                'date'=>date('Y-m-d H:i:s'),
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'id_product'=>21,
                'detail'=>'Chainsaw Man 10',
                'description'=>'Cuando su padre murió, Denji se vio obligado a saldar una gran deuda y no había forma de pagarla. Pero gracias a la ayuda de un Demonio Perro que salvó llamado Pochita, Denji es capaz de sobrevivir convirtiéndose en un Cazador de demonios a sueldo, haciendo trabajos para los Yakuza. Los poderes motosierra de Pochita son útiles contra estos poderosos demonios. Y cuando Denji termina siendo asesinado por un demonio, Pochita se sacrifica para revivirlo. Pero ahora Denji ha renacido como una especie de extraño híbrido Demonio-Humano. ¡Ahora es Chainsaw Man! Después de su transformación, es reclutado rápidamente y obligado a unirse a los Cazadores de Demonios de Seguridad Pública bajo amenaza de exterminio ya que técnicamente es un Demonio. Ahora que vive cómodamente por primera vez en su vida, Denji lucha por determinar sus sueños y establecer relaciones significativas mientras mata demonios y trabaja junto a otros excéntricos cazadores.',
                'price'=>2000,
                'image'=>'chainsawman10.jpg',
                'id_provider'=>1,
                'id_country'=>7,
                'date'=>date('Y-m-d H:i:s'),
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'id_product'=>22,
                'detail'=>'Chainsaw Man 11',
                'description'=>'Cuando su padre murió, Denji se vio obligado a saldar una gran deuda y no había forma de pagarla. Pero gracias a la ayuda de un Demonio Perro que salvó llamado Pochita, Denji es capaz de sobrevivir convirtiéndose en un Cazador de demonios a sueldo, haciendo trabajos para los Yakuza. Los poderes motosierra de Pochita son útiles contra estos poderosos demonios. Y cuando Denji termina siendo asesinado por un demonio, Pochita se sacrifica para revivirlo. Pero ahora Denji ha renacido como una especie de extraño híbrido Demonio-Humano. ¡Ahora es Chainsaw Man! Después de su transformación, es reclutado rápidamente y obligado a unirse a los Cazadores de Demonios de Seguridad Pública bajo amenaza de exterminio ya que técnicamente es un Demonio. Ahora que vive cómodamente por primera vez en su vida, Denji lucha por determinar sus sueños y establecer relaciones significativas mientras mata demonios y trabaja junto a otros excéntricos cazadores.',
                'price'=>2000,
                'image'=>'chainsawman11.jpg',
                'id_provider'=>1,
                'id_country'=>7,
                'date'=>date('Y-m-d H:i:s'),
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'id_product'=>23,
                'detail'=>'Darling in the franxx 4',
                'description'=>'Cuando su padre murió, Denji se vio obligado a saldar una gran deuda y no había forma de pagarla. Pero gracias a la ayuda de un Demonio Perro que salvó llamado Pochita, Denji es capaz de sobrevivir convirtiéndose en un Cazador de demonios a sueldo, haciendo trabajos para los Yakuza. Los poderes motosierra de Pochita son útiles contra estos poderosos demonios. Y cuando Denji termina siendo asesinado por un demonio, Pochita se sacrifica para revivirlo. Pero ahora Denji ha renacido como una especie de extraño híbrido Demonio-Humano. ¡Ahora es Chainsaw Man! Después de su transformación, es reclutado rápidamente y obligado a unirse a los Cazadores de Demonios de Seguridad Pública bajo amenaza de exterminio ya que técnicamente es un Demonio. Ahora que vive cómodamente por primera vez en su vida, Denji lucha por determinar sus sueños y establecer relaciones significativas mientras mata demonios y trabaja junto a otros excéntricos cazadores.',
                'price'=>2000,
                'image'=>'darlingInthefranxx_04.jpg',
                'id_provider'=>1,
                'id_country'=>7,
                'date'=>date('Y-m-d H:i:s'),
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'id_product'=>24,
                'detail'=>'Demon Slayer 1',
                'description'=>'Cuando su padre murió, Denji se vio obligado a saldar una gran deuda y no había forma de pagarla. Pero gracias a la ayuda de un Demonio Perro que salvó llamado Pochita, Denji es capaz de sobrevivir convirtiéndose en un Cazador de demonios a sueldo, haciendo trabajos para los Yakuza. Los poderes motosierra de Pochita son útiles contra estos poderosos demonios. Y cuando Denji termina siendo asesinado por un demonio, Pochita se sacrifica para revivirlo. Pero ahora Denji ha renacido como una especie de extraño híbrido Demonio-Humano. ¡Ahora es Chainsaw Man! Después de su transformación, es reclutado rápidamente y obligado a unirse a los Cazadores de Demonios de Seguridad Pública bajo amenaza de exterminio ya que técnicamente es un Demonio. Ahora que vive cómodamente por primera vez en su vida, Denji lucha por determinar sus sueños y establecer relaciones significativas mientras mata demonios y trabaja junto a otros excéntricos cazadores.',
                'price'=>2000,
                'image'=>'demonslayer01.jpg',
                'id_provider'=>1,
                'id_country'=>7,
                'date'=>date('Y-m-d H:i:s'),
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'id_product'=>25,
                'detail'=>'Demon Slayer 2',
                'description'=>'Cuando su padre murió, Denji se vio obligado a saldar una gran deuda y no había forma de pagarla. Pero gracias a la ayuda de un Demonio Perro que salvó llamado Pochita, Denji es capaz de sobrevivir convirtiéndose en un Cazador de demonios a sueldo, haciendo trabajos para los Yakuza. Los poderes motosierra de Pochita son útiles contra estos poderosos demonios. Y cuando Denji termina siendo asesinado por un demonio, Pochita se sacrifica para revivirlo. Pero ahora Denji ha renacido como una especie de extraño híbrido Demonio-Humano. ¡Ahora es Chainsaw Man! Después de su transformación, es reclutado rápidamente y obligado a unirse a los Cazadores de Demonios de Seguridad Pública bajo amenaza de exterminio ya que técnicamente es un Demonio. Ahora que vive cómodamente por primera vez en su vida, Denji lucha por determinar sus sueños y establecer relaciones significativas mientras mata demonios y trabaja junto a otros excéntricos cazadores.',
                'price'=>2000,
                'image'=>'demonslayer02.jpg',
                'id_provider'=>1,
                'id_country'=>7,
                'date'=>date('Y-m-d H:i:s'),
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'id_product'=>26,
                'detail'=>'Demon Slayer 3',
                'description'=>'Cuando su padre murió, Denji se vio obligado a saldar una gran deuda y no había forma de pagarla. Pero gracias a la ayuda de un Demonio Perro que salvó llamado Pochita, Denji es capaz de sobrevivir convirtiéndose en un Cazador de demonios a sueldo, haciendo trabajos para los Yakuza. Los poderes motosierra de Pochita son útiles contra estos poderosos demonios. Y cuando Denji termina siendo asesinado por un demonio, Pochita se sacrifica para revivirlo. Pero ahora Denji ha renacido como una especie de extraño híbrido Demonio-Humano. ¡Ahora es Chainsaw Man! Después de su transformación, es reclutado rápidamente y obligado a unirse a los Cazadores de Demonios de Seguridad Pública bajo amenaza de exterminio ya que técnicamente es un Demonio. Ahora que vive cómodamente por primera vez en su vida, Denji lucha por determinar sus sueños y establecer relaciones significativas mientras mata demonios y trabaja junto a otros excéntricos cazadores.',
                'price'=>2000,
                'image'=>'demonslayer03.jpg',
                'id_provider'=>1,
                'id_country'=>7,
                'date'=>date('Y-m-d H:i:s'),
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'id_product'=>27,
                'detail'=>'Demon Slayer 4',
                'description'=>'Cuando su padre murió, Denji se vio obligado a saldar una gran deuda y no había forma de pagarla. Pero gracias a la ayuda de un Demonio Perro que salvó llamado Pochita, Denji es capaz de sobrevivir convirtiéndose en un Cazador de demonios a sueldo, haciendo trabajos para los Yakuza. Los poderes motosierra de Pochita son útiles contra estos poderosos demonios. Y cuando Denji termina siendo asesinado por un demonio, Pochita se sacrifica para revivirlo. Pero ahora Denji ha renacido como una especie de extraño híbrido Demonio-Humano. ¡Ahora es Chainsaw Man! Después de su transformación, es reclutado rápidamente y obligado a unirse a los Cazadores de Demonios de Seguridad Pública bajo amenaza de exterminio ya que técnicamente es un Demonio. Ahora que vive cómodamente por primera vez en su vida, Denji lucha por determinar sus sueños y establecer relaciones significativas mientras mata demonios y trabaja junto a otros excéntricos cazadores.',
                'price'=>2000,
                'image'=>'demonslayer04.jpg',
                'id_provider'=>1,
                'id_country'=>7,
                'date'=>date('Y-m-d H:i:s'),
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'id_product'=>28,
                'detail'=>'Demon Slayer 5',
                'description'=>'Cuando su padre murió, Denji se vio obligado a saldar una gran deuda y no había forma de pagarla. Pero gracias a la ayuda de un Demonio Perro que salvó llamado Pochita, Denji es capaz de sobrevivir convirtiéndose en un Cazador de demonios a sueldo, haciendo trabajos para los Yakuza. Los poderes motosierra de Pochita son útiles contra estos poderosos demonios. Y cuando Denji termina siendo asesinado por un demonio, Pochita se sacrifica para revivirlo. Pero ahora Denji ha renacido como una especie de extraño híbrido Demonio-Humano. ¡Ahora es Chainsaw Man! Después de su transformación, es reclutado rápidamente y obligado a unirse a los Cazadores de Demonios de Seguridad Pública bajo amenaza de exterminio ya que técnicamente es un Demonio. Ahora que vive cómodamente por primera vez en su vida, Denji lucha por determinar sus sueños y establecer relaciones significativas mientras mata demonios y trabaja junto a otros excéntricos cazadores.',
                'price'=>2000,
                'image'=>'demonslayer05.jpg',
                'id_provider'=>1,
                'id_country'=>7,
                'date'=>date('Y-m-d H:i:s'),
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'id_product'=>29,
                'detail'=>'Demon Slayer 6',
                'description'=>'Cuando su padre murió, Denji se vio obligado a saldar una gran deuda y no había forma de pagarla. Pero gracias a la ayuda de un Demonio Perro que salvó llamado Pochita, Denji es capaz de sobrevivir convirtiéndose en un Cazador de demonios a sueldo, haciendo trabajos para los Yakuza. Los poderes motosierra de Pochita son útiles contra estos poderosos demonios. Y cuando Denji termina siendo asesinado por un demonio, Pochita se sacrifica para revivirlo. Pero ahora Denji ha renacido como una especie de extraño híbrido Demonio-Humano. ¡Ahora es Chainsaw Man! Después de su transformación, es reclutado rápidamente y obligado a unirse a los Cazadores de Demonios de Seguridad Pública bajo amenaza de exterminio ya que técnicamente es un Demonio. Ahora que vive cómodamente por primera vez en su vida, Denji lucha por determinar sus sueños y establecer relaciones significativas mientras mata demonios y trabaja junto a otros excéntricos cazadores.',
                'price'=>2000,
                'image'=>'demonslayer06.jpg',
                'id_provider'=>1,
                'id_country'=>7,
                'date'=>date('Y-m-d H:i:s'),
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'id_product'=>30,
                'detail'=>'Demon Slayer 7',
                'description'=>'Cuando su padre murió, Denji se vio obligado a saldar una gran deuda y no había forma de pagarla. Pero gracias a la ayuda de un Demonio Perro que salvó llamado Pochita, Denji es capaz de sobrevivir convirtiéndose en un Cazador de demonios a sueldo, haciendo trabajos para los Yakuza. Los poderes motosierra de Pochita son útiles contra estos poderosos demonios. Y cuando Denji termina siendo asesinado por un demonio, Pochita se sacrifica para revivirlo. Pero ahora Denji ha renacido como una especie de extraño híbrido Demonio-Humano. ¡Ahora es Chainsaw Man! Después de su transformación, es reclutado rápidamente y obligado a unirse a los Cazadores de Demonios de Seguridad Pública bajo amenaza de exterminio ya que técnicamente es un Demonio. Ahora que vive cómodamente por primera vez en su vida, Denji lucha por determinar sus sueños y establecer relaciones significativas mientras mata demonios y trabaja junto a otros excéntricos cazadores.',
                'price'=>2000,
                'image'=>'demonslayer07.jpg',
                'id_provider'=>1,
                'id_country'=>7,
                'date'=>date('Y-m-d H:i:s'),
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'id_product'=>31,
                'detail'=>'Demon Slayer 8',
                'description'=>'Cuando su padre murió, Denji se vio obligado a saldar una gran deuda y no había forma de pagarla. Pero gracias a la ayuda de un Demonio Perro que salvó llamado Pochita, Denji es capaz de sobrevivir convirtiéndose en un Cazador de demonios a sueldo, haciendo trabajos para los Yakuza. Los poderes motosierra de Pochita son útiles contra estos poderosos demonios. Y cuando Denji termina siendo asesinado por un demonio, Pochita se sacrifica para revivirlo. Pero ahora Denji ha renacido como una especie de extraño híbrido Demonio-Humano. ¡Ahora es Chainsaw Man! Después de su transformación, es reclutado rápidamente y obligado a unirse a los Cazadores de Demonios de Seguridad Pública bajo amenaza de exterminio ya que técnicamente es un Demonio. Ahora que vive cómodamente por primera vez en su vida, Denji lucha por determinar sus sueños y establecer relaciones significativas mientras mata demonios y trabaja junto a otros excéntricos cazadores.',
                'price'=>2000,
                'image'=>'demonslayer08.jpg',
                'id_provider'=>1,
                'id_country'=>7,
                'date'=>date('Y-m-d H:i:s'),
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'id_product'=>32,
                'detail'=>'Demon Slayer 9',
                'description'=>'Cuando su padre murió, Denji se vio obligado a saldar una gran deuda y no había forma de pagarla. Pero gracias a la ayuda de un Demonio Perro que salvó llamado Pochita, Denji es capaz de sobrevivir convirtiéndose en un Cazador de demonios a sueldo, haciendo trabajos para los Yakuza. Los poderes motosierra de Pochita son útiles contra estos poderosos demonios. Y cuando Denji termina siendo asesinado por un demonio, Pochita se sacrifica para revivirlo. Pero ahora Denji ha renacido como una especie de extraño híbrido Demonio-Humano. ¡Ahora es Chainsaw Man! Después de su transformación, es reclutado rápidamente y obligado a unirse a los Cazadores de Demonios de Seguridad Pública bajo amenaza de exterminio ya que técnicamente es un Demonio. Ahora que vive cómodamente por primera vez en su vida, Denji lucha por determinar sus sueños y establecer relaciones significativas mientras mata demonios y trabaja junto a otros excéntricos cazadores.',
                'price'=>2000,
                'image'=>'demonslayer09.jpg',
                'id_provider'=>1,
                'id_country'=>7,
                'date'=>date('Y-m-d H:i:s'),
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'id_product'=>33,
                'detail'=>'Demon Slayer 10',
                'description'=>'Cuando su padre murió, Denji se vio obligado a saldar una gran deuda y no había forma de pagarla. Pero gracias a la ayuda de un Demonio Perro que salvó llamado Pochita, Denji es capaz de sobrevivir convirtiéndose en un Cazador de demonios a sueldo, haciendo trabajos para los Yakuza. Los poderes motosierra de Pochita son útiles contra estos poderosos demonios. Y cuando Denji termina siendo asesinado por un demonio, Pochita se sacrifica para revivirlo. Pero ahora Denji ha renacido como una especie de extraño híbrido Demonio-Humano. ¡Ahora es Chainsaw Man! Después de su transformación, es reclutado rápidamente y obligado a unirse a los Cazadores de Demonios de Seguridad Pública bajo amenaza de exterminio ya que técnicamente es un Demonio. Ahora que vive cómodamente por primera vez en su vida, Denji lucha por determinar sus sueños y establecer relaciones significativas mientras mata demonios y trabaja junto a otros excéntricos cazadores.',
                'price'=>2000,
                'image'=>'demonslayer10.jpg',
                'id_provider'=>1,
                'id_country'=>7,
                'date'=>date('Y-m-d H:i:s'),
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'id_product'=>34,
                'detail'=>'Demon Slayer 11',
                'description'=>'Cuando su padre murió, Denji se vio obligado a saldar una gran deuda y no había forma de pagarla. Pero gracias a la ayuda de un Demonio Perro que salvó llamado Pochita, Denji es capaz de sobrevivir convirtiéndose en un Cazador de demonios a sueldo, haciendo trabajos para los Yakuza. Los poderes motosierra de Pochita son útiles contra estos poderosos demonios. Y cuando Denji termina siendo asesinado por un demonio, Pochita se sacrifica para revivirlo. Pero ahora Denji ha renacido como una especie de extraño híbrido Demonio-Humano. ¡Ahora es Chainsaw Man! Después de su transformación, es reclutado rápidamente y obligado a unirse a los Cazadores de Demonios de Seguridad Pública bajo amenaza de exterminio ya que técnicamente es un Demonio. Ahora que vive cómodamente por primera vez en su vida, Denji lucha por determinar sus sueños y establecer relaciones significativas mientras mata demonios y trabaja junto a otros excéntricos cazadores.',
                'price'=>2000,
                'image'=>'demonslayer11.jpg',
                'id_provider'=>1,
                'id_country'=>7,
                'date'=>date('Y-m-d H:i:s'),
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'id_product'=>35,
                'detail'=>'Demon Slayer 12',
                'description'=>'Cuando su padre murió, Denji se vio obligado a saldar una gran deuda y no había forma de pagarla. Pero gracias a la ayuda de un Demonio Perro que salvó llamado Pochita, Denji es capaz de sobrevivir convirtiéndose en un Cazador de demonios a sueldo, haciendo trabajos para los Yakuza. Los poderes motosierra de Pochita son útiles contra estos poderosos demonios. Y cuando Denji termina siendo asesinado por un demonio, Pochita se sacrifica para revivirlo. Pero ahora Denji ha renacido como una especie de extraño híbrido Demonio-Humano. ¡Ahora es Chainsaw Man! Después de su transformación, es reclutado rápidamente y obligado a unirse a los Cazadores de Demonios de Seguridad Pública bajo amenaza de exterminio ya que técnicamente es un Demonio. Ahora que vive cómodamente por primera vez en su vida, Denji lucha por determinar sus sueños y establecer relaciones significativas mientras mata demonios y trabaja junto a otros excéntricos cazadores.',
                'price'=>2000,
                'image'=>'demonslayer12.jpg',
                'id_provider'=>1,
                'id_country'=>7,
                'date'=>date('Y-m-d H:i:s'),
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'id_product'=>36,
                'detail'=>'Demon Slayer 13',
                'description'=>'Cuando su padre murió, Denji se vio obligado a saldar una gran deuda y no había forma de pagarla. Pero gracias a la ayuda de un Demonio Perro que salvó llamado Pochita, Denji es capaz de sobrevivir convirtiéndose en un Cazador de demonios a sueldo, haciendo trabajos para los Yakuza. Los poderes motosierra de Pochita son útiles contra estos poderosos demonios. Y cuando Denji termina siendo asesinado por un demonio, Pochita se sacrifica para revivirlo. Pero ahora Denji ha renacido como una especie de extraño híbrido Demonio-Humano. ¡Ahora es Chainsaw Man! Después de su transformación, es reclutado rápidamente y obligado a unirse a los Cazadores de Demonios de Seguridad Pública bajo amenaza de exterminio ya que técnicamente es un Demonio. Ahora que vive cómodamente por primera vez en su vida, Denji lucha por determinar sus sueños y establecer relaciones significativas mientras mata demonios y trabaja junto a otros excéntricos cazadores.',
                'price'=>2000,
                'image'=>'demonslayer13.jpg',
                'id_provider'=>1,
                'id_country'=>7,
                'date'=>date('Y-m-d H:i:s'),
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'id_product'=>37,
                'detail'=>'Demon Slayer 14',
                'description'=>'Cuando su padre murió, Denji se vio obligado a saldar una gran deuda y no había forma de pagarla. Pero gracias a la ayuda de un Demonio Perro que salvó llamado Pochita, Denji es capaz de sobrevivir convirtiéndose en un Cazador de demonios a sueldo, haciendo trabajos para los Yakuza. Los poderes motosierra de Pochita son útiles contra estos poderosos demonios. Y cuando Denji termina siendo asesinado por un demonio, Pochita se sacrifica para revivirlo. Pero ahora Denji ha renacido como una especie de extraño híbrido Demonio-Humano. ¡Ahora es Chainsaw Man! Después de su transformación, es reclutado rápidamente y obligado a unirse a los Cazadores de Demonios de Seguridad Pública bajo amenaza de exterminio ya que técnicamente es un Demonio. Ahora que vive cómodamente por primera vez en su vida, Denji lucha por determinar sus sueños y establecer relaciones significativas mientras mata demonios y trabaja junto a otros excéntricos cazadores.',
                'price'=>2000,
                'image'=>'demonslayer14.jpg',
                'id_provider'=>1,
                'id_country'=>7,
                'date'=>date('Y-m-d H:i:s'),
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'id_product'=>38,
                'detail'=>'Demon Slayer 15',
                'description'=>'Cuando su padre murió, Denji se vio obligado a saldar una gran deuda y no había forma de pagarla. Pero gracias a la ayuda de un Demonio Perro que salvó llamado Pochita, Denji es capaz de sobrevivir convirtiéndose en un Cazador de demonios a sueldo, haciendo trabajos para los Yakuza. Los poderes motosierra de Pochita son útiles contra estos poderosos demonios. Y cuando Denji termina siendo asesinado por un demonio, Pochita se sacrifica para revivirlo. Pero ahora Denji ha renacido como una especie de extraño híbrido Demonio-Humano. ¡Ahora es Chainsaw Man! Después de su transformación, es reclutado rápidamente y obligado a unirse a los Cazadores de Demonios de Seguridad Pública bajo amenaza de exterminio ya que técnicamente es un Demonio. Ahora que vive cómodamente por primera vez en su vida, Denji lucha por determinar sus sueños y establecer relaciones significativas mientras mata demonios y trabaja junto a otros excéntricos cazadores.',
                'price'=>2000,
                'image'=>'demonslayer15.jpg',
                'id_provider'=>1,
                'id_country'=>7,
                'date'=>date('Y-m-d H:i:s'),
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'id_product'=>39,
                'detail'=>'Demon Slayer 16',
                'description'=>'Cuando su padre murió, Denji se vio obligado a saldar una gran deuda y no había forma de pagarla. Pero gracias a la ayuda de un Demonio Perro que salvó llamado Pochita, Denji es capaz de sobrevivir convirtiéndose en un Cazador de demonios a sueldo, haciendo trabajos para los Yakuza. Los poderes motosierra de Pochita son útiles contra estos poderosos demonios. Y cuando Denji termina siendo asesinado por un demonio, Pochita se sacrifica para revivirlo. Pero ahora Denji ha renacido como una especie de extraño híbrido Demonio-Humano. ¡Ahora es Chainsaw Man! Después de su transformación, es reclutado rápidamente y obligado a unirse a los Cazadores de Demonios de Seguridad Pública bajo amenaza de exterminio ya que técnicamente es un Demonio. Ahora que vive cómodamente por primera vez en su vida, Denji lucha por determinar sus sueños y establecer relaciones significativas mientras mata demonios y trabaja junto a otros excéntricos cazadores.',
                'price'=>2000,
                'image'=>'demonslayer16.jpg',
                'id_provider'=>1,
                'id_country'=>7,
                'date'=>date('Y-m-d H:i:s'),
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'id_product'=>40,
                'detail'=>'Demon Slayer 17',
                'description'=>'Cuando su padre murió, Denji se vio obligado a saldar una gran deuda y no había forma de pagarla. Pero gracias a la ayuda de un Demonio Perro que salvó llamado Pochita, Denji es capaz de sobrevivir convirtiéndose en un Cazador de demonios a sueldo, haciendo trabajos para los Yakuza. Los poderes motosierra de Pochita son útiles contra estos poderosos demonios. Y cuando Denji termina siendo asesinado por un demonio, Pochita se sacrifica para revivirlo. Pero ahora Denji ha renacido como una especie de extraño híbrido Demonio-Humano. ¡Ahora es Chainsaw Man! Después de su transformación, es reclutado rápidamente y obligado a unirse a los Cazadores de Demonios de Seguridad Pública bajo amenaza de exterminio ya que técnicamente es un Demonio. Ahora que vive cómodamente por primera vez en su vida, Denji lucha por determinar sus sueños y establecer relaciones significativas mientras mata demonios y trabaja junto a otros excéntricos cazadores.',
                'price'=>2000,
                'image'=>'demonslayer17.jpg',
                'id_provider'=>1,
                'id_country'=>7,
                'date'=>date('Y-m-d H:i:s'),
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
        ]);
    }
}
